### ISSUE TITLE
Feature request: differentiated highlighting

### ISSUE THREAD

**Issue by hmijail** [dstein64/highlight#1]
Would be great to have each click of the marker result in a different color/shadow of highlighting, so it remains clear what parts are (supposed to be) more or less important. 
Looking forward to further summarization algorithms! :)

**Comment by dstein64** [comment]
Cool idea. Thanks! I've added this functionality, which can be enabled by selecting "Tinted Highlights" on the extension's options page. The update should be available shortly for Chrome and Firefox (pending the corresponding extension reviews).
