### ISSUE TITLE
Feature request: keep state globally

### ISSUE THREAD

**Issue by hmijail** [dstein64/highlight#2]
Currently, the highlighting only applies to the current page in the current tab.
Would be great to have the highlighting globally enabled (all pages, all tabs).

**Comment by dstein64** [comment]
Another nice idea. Thanks again!

I've added this functionality. Global highlighting can be applied on the extension's options page.

The update should be available shortly for Firefox, pending the corresponding extension review. It will be some more time until it's available on Chrome, as my update from yesterday is still in review, and it's seemingly not possible to make edits while this is occurring (even though I have a newer extension ready which obviates the need for the existing review).

**Comment by hmijail** [comment]
Global highlighting is not working.
When I updated to 1.9.0 I *seem* to remember that it did, but the truth is that I'm not sure...
I'm in Firefox 75.0b11.

**Comment by dstein64** [comment]
I was not able to replicate the issue on Firefox 74 of Firefox 75 on Ubuntu.

Can you try with freshly loaded tabs, by clicking the empty highlighter for global highlighting?

I've found that Firefox may unload tabs to conserve memory, or may not reload all tabs when restarting the browser. These tabs are unable to be globally highlighted, but tabs that are loaded in memory are working fine in my experiments.
